apiVersion: v2
name: stakater-nordmart-review
description: A Helm chart for Kubernetes
dependencies:
- name: mongodb
  version: 12.1.15
  repository: "https://raw.githubusercontent.com/bitnami/charts/defb094c658024e4aa8245622dab202874880cbc/bitnami"
- name: application
  version: 1.1.14
  repository: https://stakater.github.io/stakater-charts  

# DON'T TOUCH THIS
# This is the chart version. This version number is incremented automatically each time you make changes
# to the application or helm values file; and pushed to artifact store
version: 0.0.0
