apiVersion: v2
name: stakater-nordmart-review
description: A Helm chart for Kubernetes
dependencies:
- name: mongodb
  version: 10.0.5
  repository: "https://charts.bitnami.com/bitnami"
- name: application
  version: 1.0.*
  repository: https://stakater.github.io/stakater-charts  

# DON'T TOUCH THIS
# This is the chart version. This version number is incremented automatically each time you make changes
# to the application or helm values file; and pushed to artifact store
version: 0.0.0
