apiVersion: v2
name: stakater-nordmart-review
description: A Helm chart for Kubernetes
dependencies:
- name: mongodb
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 13.15.4
- alias: review-api
  name: application
  repository: https://stakater.github.io/stakater-charts
  version: 2.1.18

# DON'T TOUCH THIS
# This is the chart version. This version number is incremented automatically each time you make changes
# to the application or helm values file; and pushed to artifact store
version: 0.0.0
